nodes:
  - 127.0.0.1
  - 127.0.0.1
  - 127.0.0.1
  - 127.0.0.1
  - 127.0.0.1  
# Gossip configuration
gossip:
  port_range:
    start: 10010
    end: 10060

# Raft / service ports
ports:
  peer: 10000
  client: 10105

# Paths
output_dir: /var/niova/cp
bin_dir: /usr/local/bin/niova
lib_dir: /usr/local/lib
