%global pkg_name     niova-mdsvc
%global niova_libdir %{_libdir}/niova-mdsvc
%global niova_build  %{_builddir}/niova-c-build

Name:           %{pkg_name}
Version:        %{version}
Release:        1%{?dist}
Summary:        Niova Metadata Service Control Plane
License:        Apache-2.0
URL:            https://github.com/00pauln00/niova-mdsvc
ExclusiveArch:  aarch64

# ---------------------------------------------------------------------------
# Build-time requirements
# ---------------------------------------------------------------------------
# C build chain
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool
BuildRequires:  git
BuildRequires:  openssl-devel
BuildRequires:  libuuid-devel
BuildRequires:  libgcrypt-devel
BuildRequires:  rocksdb-devel

# Go toolchain — must be >= 1.24; install from upstream if not in repos.
# Verify with: go version
BuildRequires:  golang >= 1.24

# ---------------------------------------------------------------------------
# Runtime requirements
# ---------------------------------------------------------------------------
# rocksdb-libs ships librocksdb.so linked by niova-core at build time.
Requires:       rocksdb-libs
# Standard system libs (present on every Rocky 9 install)
Requires:       openssl-libs
Requires:       libuuid
# uuidgen is used in gen_raft_cfgs.sh
Requires:       util-linux

%description
Control plane for the Niova distributed metadata service (aarch64).

Provides the following binaries:
  CTLPlane_pmdbServer  - Raft/PMDB consensus server
  CTLPlane_proxy       - HTTP API gateway (service discovery via Serf gossip)
  cp-monitor           - Prometheus metrics exporter
  niova-ctl            - TUI cluster management tool
  cc-manager           - NISD container configuration manager
  cfgApp               - Port-range configuration utility

Bundles the niova-core, niova-raft, and niova-pumicedb C shared libraries
in %{niova_libdir}, registered with ldconfig. No separate library packages
are required.

Deployment is managed by systemd. Before starting services, configure
/etc/niova/niova.env with the cluster identity values generated by
/usr/share/niova-mdsvc/scripts/gen_raft_cfgs.sh.

# ---------------------------------------------------------------------------
# %prep
# Build-in-place mode: rpmbuild runs directly inside the git repo.
# Submodules are initialized by the Makefile before invoking rpmbuild.
# %setup / %autosetup are not used — there is no tarball to extract.
# ---------------------------------------------------------------------------
%prep
# Verify submodules are present — fail early with a clear message.
CORE_DIR="modules/niova-pumicedb/modules/niova-raft/modules/niova-core"
if [ ! -f "${CORE_DIR}/configure.ac" ] && [ ! -f "${CORE_DIR}/configure.in" ]; then
    echo "ERROR: Git submodules are not initialized." >&2
    echo "Run: git submodule update --init --recursive" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# %build
# ---------------------------------------------------------------------------
%build

# ── Architecture-specific settings ──────────────────────────────────────────
export GOARCH=arm64
export GOOS=linux
export CGO_ENABLED=1

# ── Build all C dependency libraries ────────────────────────────────────────
mkdir -p %{niova_build}
bash packaging/build-c-deps.sh %{niova_build} %{?_smp_mflags:-j}$(nproc)

# ── Build Go binaries ────────────────────────────────────────────────────────
# CGO flags point at the freshly-built C libraries.
export CGO_LDFLAGS="-L%{niova_build}/lib"
export CGO_CFLAGS="-I%{niova_build}/include"
export LD_LIBRARY_PATH="%{niova_build}/lib"

mkdir -p libexec

# Production CP binaries only — testApp and ncpc are intentionally excluded.
go build -o libexec/CTLPlane_pmdbServer  ./controlplane/pmdbServer/
go build -o libexec/CTLPlane_proxy       ./controlplane/proxy/
go build -o libexec/cp-monitor           ./controlplane/monitor/
go build -o libexec/niova-ctl            ./controlplane/niova-ctl/
go build -o libexec/cc-manager           ./controlplane/containerConfigManager/
go build -o libexec/cfgApp               ./controlplane/configApplication/

# ---------------------------------------------------------------------------
# %install
# ---------------------------------------------------------------------------
%install

# ── Go binaries ─────────────────────────────────────────────────────────────
install -d %{buildroot}/usr/libexec/niova
install -m 0755 libexec/CTLPlane_pmdbServer  %{buildroot}/usr/libexec/niova/
install -m 0755 libexec/CTLPlane_proxy       %{buildroot}/usr/libexec/niova/
install -m 0755 libexec/cp-monitor           %{buildroot}/usr/libexec/niova/
install -m 0755 libexec/niova-ctl            %{buildroot}/usr/libexec/niova/
install -m 0755 libexec/cc-manager           %{buildroot}/usr/libexec/niova/
install -m 0755 libexec/cfgApp               %{buildroot}/usr/libexec/niova/

# ── Bundled C shared libraries ───────────────────────────────────────────────
# Installed to a private directory to avoid conflicts with system libraries.
install -d %{buildroot}%{niova_libdir}

# Copy regular files (.so.X.Y.Z)
find %{niova_build}/lib -maxdepth 1 -name '*.so*' -type f \
    -exec install -m 0755 {} %{buildroot}%{niova_libdir}/ \;

# Preserve symlinks (libXXX.so -> libXXX.so.1 -> libXXX.so.1.0.0)
find %{niova_build}/lib -maxdepth 1 -name '*.so*' -type l \
    -exec cp -a {} %{buildroot}%{niova_libdir}/ \;

# ── ldconfig drop-in ────────────────────────────────────────────────────────
install -d %{buildroot}/etc/ld.so.conf.d
install -m 0644 packaging/niova-mdsvc.conf \
    %{buildroot}/etc/ld.so.conf.d/niova-mdsvc.conf

# ── Scripts ─────────────────────────────────────────────────────────────────
install -d %{buildroot}/usr/share/niova-mdsvc/scripts
install -m 0755 scripts/deploy/start_pumice.sh \
    %{buildroot}/usr/share/niova-mdsvc/scripts/
install -m 0755 scripts/deploy/gen_raft_cfgs.sh \
    %{buildroot}/usr/share/niova-mdsvc/scripts/
install -m 0755 scripts/deploy/deploy.sh \
    %{buildroot}/usr/share/niova-mdsvc/scripts/

# ── Config example ──────────────────────────────────────────────────────────
install -m 0644 scripts/deploy/config.yaml \
    %{buildroot}/usr/share/niova-mdsvc/scripts/config.yaml.example

# ── systemd unit files ──────────────────────────────────────────────────────
install -d %{buildroot}/usr/lib/systemd/system
install -m 0644 packaging/niova-pmdbserver.service \
    %{buildroot}/usr/lib/systemd/system/
install -m 0644 packaging/niova-proxy.service \
    %{buildroot}/usr/lib/systemd/system/
install -m 0644 packaging/niova-monitor.service \
    %{buildroot}/usr/lib/systemd/system/

# ── Environment / config file ────────────────────────────────────────────────
install -d %{buildroot}/etc/niova
install -m 0640 packaging/niova.env %{buildroot}/etc/niova/niova.env

# ── Runtime directories ──────────────────────────────────────────────────────
# Ownership is set in %post after the niova user is created.
install -d %{buildroot}/var/log/niova
install -d %{buildroot}/var/lib/niova
install -d %{buildroot}/var/lib/niova/configs
install -d %{buildroot}/var/lib/niova/ctl
install -d %{buildroot}/var/lib/niova/db

# ---------------------------------------------------------------------------
# %pre — runs before files are installed
# ---------------------------------------------------------------------------
%pre
# Create the dedicated service user and group on first install (if absent).
getent group  niova > /dev/null || groupadd -r niova
getent passwd niova > /dev/null || \
    useradd -r -g niova \
            -d /var/lib/niova \
            -s /sbin/nologin \
            -c "Niova Control Plane service account" \
            niova

# ---------------------------------------------------------------------------
# %post — runs after files are installed
# ---------------------------------------------------------------------------
%post
# Register the bundled C libraries with the dynamic linker.
/sbin/ldconfig

# Set ownership of runtime directories.
chown -R niova:niova /var/log/niova /var/lib/niova

# If USER_ENCRYPTION_KEY is not set in the env file, generate one now.
# This runs only on fresh installs (the file is %config(noreplace) so
# upgrades do not overwrite an operator's existing key).
if grep -q '^USER_ENCRYPTION_KEY=$' /etc/niova/niova.env 2>/dev/null; then
    GENERATED_KEY="$(openssl rand -base64 32)"
    sed -i "s|^USER_ENCRYPTION_KEY=$|USER_ENCRYPTION_KEY=${GENERATED_KEY}|" \
        /etc/niova/niova.env
    chown root:niova /etc/niova/niova.env
    echo "niova-mdsvc: generated USER_ENCRYPTION_KEY in /etc/niova/niova.env"
fi

# Notify systemd about the new unit files but do NOT enable or start them.
# The operator must populate /etc/niova/niova.env with RAFT_UUID, PEER_UUID,
# and CLIENT_UUID before starting, then run:
#   systemctl enable --now niova-pmdbserver niova-proxy niova-monitor
%systemd_post niova-pmdbserver.service niova-proxy.service niova-monitor.service

echo ""
echo "==> niova-mdsvc installed. Before starting services:"
echo "    1. Run gen_raft_cfgs.sh to create configs:"
echo "         /usr/share/niova-mdsvc/scripts/gen_raft_cfgs.sh <config.yaml>"
echo "    2. Copy generated files to /var/lib/niova/configs/"
echo "    3. Edit /etc/niova/niova.env — set RAFT_UUID, PEER_UUID, CLIENT_UUID"
echo "    4. systemctl enable --now niova-pmdbserver niova-proxy niova-monitor"
echo ""

# ---------------------------------------------------------------------------
# %preun — runs before package removal
# ---------------------------------------------------------------------------
%preun
%systemd_preun niova-pmdbserver.service niova-proxy.service niova-monitor.service

# ---------------------------------------------------------------------------
# %postun — runs after package removal
# ---------------------------------------------------------------------------
%postun
# Refresh ldconfig to remove the private lib dir from the cache.
/sbin/ldconfig
%systemd_postun_with_restart niova-pmdbserver.service \
                              niova-proxy.service \
                              niova-monitor.service

# ---------------------------------------------------------------------------
# %files
# ---------------------------------------------------------------------------
%files

# Go binaries
%dir /usr/libexec/niova
/usr/libexec/niova/CTLPlane_pmdbServer
/usr/libexec/niova/CTLPlane_proxy
/usr/libexec/niova/cp-monitor
/usr/libexec/niova/niova-ctl
/usr/libexec/niova/cc-manager
/usr/libexec/niova/cfgApp

# Bundled C libraries (private dir, registered via ldconfig)
%dir %{niova_libdir}
%{niova_libdir}/*.so*

# ldconfig drop-in
/etc/ld.so.conf.d/niova-mdsvc.conf

# Scripts and example config
%dir /usr/share/niova-mdsvc
%dir /usr/share/niova-mdsvc/scripts
/usr/share/niova-mdsvc/scripts/start_pumice.sh
/usr/share/niova-mdsvc/scripts/gen_raft_cfgs.sh
/usr/share/niova-mdsvc/scripts/deploy.sh
/usr/share/niova-mdsvc/scripts/config.yaml.example

# systemd units
/usr/lib/systemd/system/niova-pmdbserver.service
/usr/lib/systemd/system/niova-proxy.service
/usr/lib/systemd/system/niova-monitor.service

# Environment file — noreplace: upgrades preserve operator edits
%dir /etc/niova
%config(noreplace) /etc/niova/niova.env

# Runtime directories owned by the niova user
%attr(0755, niova, niova) %dir /var/log/niova
%attr(0755, niova, niova) %dir /var/lib/niova
%attr(0750, niova, niova) %dir /var/lib/niova/configs
%attr(0750, niova, niova) %dir /var/lib/niova/ctl
%attr(0750, niova, niova) %dir /var/lib/niova/db

# ---------------------------------------------------------------------------
# %changelog
# ---------------------------------------------------------------------------
%changelog
* Tue Apr 08 2026 Niova Build System <build@niova.io> - 1.0.0-1
- Initial RPM release
- Bundles niova-core, niova-raft, niova-pumicedb C libraries
- systemd-managed deployment (niova-pmdbserver, niova-proxy, niova-monitor)
- aarch64 build
