%global pkg_name     niova-mdsvc
%global niova_libdir /var/niova/lib
%global niova_build  %{_builddir}/niova-mdsvc-build
%{!?niova_core: %global niova_core /var/niova}

Name:           %{pkg_name}
Version:        %{version}
Release:        1%{?dist}
Summary:        Niova Metadata Service Control Plane
License:        Apache-2.0
URL:            https://github.com/00pauln00/niova-mdsvc
ExclusiveArch:  x86_64

# ---------------------------------------------------------------------------
# Build-time requirements
# ---------------------------------------------------------------------------
# C build chain
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool
BuildRequires:  git
BuildRequires:  openssl-devel
BuildRequires:  libuuid-devel
BuildRequires:  libgcrypt-devel
BuildRequires:  rocksdb-devel

# niova-core provides libniova*.so and headers under /opt/niova-core
BuildRequires:  niova-core

# Go toolchain — must be >= 1.24; install from upstream if not in repos.
# Verify with: go version
BuildRequires:  golang >= 1.24

# ---------------------------------------------------------------------------
# Runtime requirements
# ---------------------------------------------------------------------------
# niova-core provides the base Niova C runtime (libniova*.so, libbacktrace.so)
Requires:       niova-core
# rocksdb-libs ships librocksdb.so linked by niova-pumicedb at build time.
# Requires:       rocksdb-libs
# Standard system libs (present on every Rocky 9 install)
Requires:       openssl-libs
Requires:       libuuid
# uuidgen is used in gen_raft_cfgs.sh
Requires:       util-linux

%description
Control plane for the Niova distributed metadata service (x86_64).

Provides the following binaries:
  CTLPlane_pmdbServer  - Raft/PMDB consensus server
  CTLPlane_proxy       - HTTP API gateway (service discovery via Serf gossip)
  cp-monitor           - Prometheus metrics exporter
  cc-manager           - NISD container configuration manager

Bundles the niova-raft and niova-pumicedb C shared libraries in
%{niova_libdir}, registered with ldconfig. The base niova-core libraries
are provided by the niova-core package.

Deployment is managed by systemd. Before starting services, configure
/etc/niova/niova.env with the cluster identity values generated by
/usr/share/niova-mdsvc/scripts/gen_raft_cfgs.sh.

# ---------------------------------------------------------------------------
# prep
# Build-in-place mode: rpmbuild runs directly inside the git repo.
# Submodules are initialized by the Makefile before invoking rpmbuild.
# ---------------------------------------------------------------------------
%prep
# Verify submodules are present — fail early with a clear message.
PUMICEDB_DIR="modules/niova-pumicedb"
RAFT_DIR="${PUMICEDB_DIR}/modules/niova-raft"
if [ ! -f "${RAFT_DIR}/configure.ac" ] && [ ! -f "${RAFT_DIR}/configure.in" ]; then
    echo "ERROR: Git submodules are not initialized." >&2
    echo "Run: git submodule update --init --recursive" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------
%build

# ── Architecture-specific settings ──────────────────────────────────────────
export GOARCH=amd64
export GOOS=linux
export CGO_ENABLED=1

# ── Build niova-raft and niova-pumicedb against installed niova-core ─────────
mkdir -p %{niova_build}
bash packaging/build-c-deps.sh %{niova_build} %{niova_core} %{?_smp_mflags}

# ── Build Go binaries ────────────────────────────────────────────────────────
# CGO flags: pumicedb/raft libs from niova_build; niova-core headers from niova_core.
export CGO_LDFLAGS="-L%{niova_build}/lib -L%{niova_core}/lib"
export CGO_CFLAGS="-I%{niova_build}/include -I%{niova_core}/include"
export LD_LIBRARY_PATH="%{niova_build}/lib:%{niova_core}/lib"

mkdir -p libexec

# Production CP binaries only — testApp and ncpc are intentionally excluded.
go build -o libexec/CTLPlane_pmdbServer  ./controlplane/pmdbServer/
go build -o libexec/CTLPlane_proxy       ./controlplane/proxy/
go build -o libexec/cp-monitor           ./controlplane/monitor/
go build -o libexec/cc-manager           ./controlplane/containerConfigManager/

# ---------------------------------------------------------------------------
# install
# ---------------------------------------------------------------------------
%install

# ── Go binaries ─────────────────────────────────────────────────────────────
install -d %{buildroot}/usr/local/bin/niova
install -m 0755 libexec/CTLPlane_pmdbServer  %{buildroot}/usr/local/bin/niova/
install -m 0755 libexec/CTLPlane_proxy       %{buildroot}/usr/local/bin/niova/
install -m 0755 libexec/cp-monitor           %{buildroot}/usr/local/bin/niova/
install -m 0755 libexec/cc-manager           %{buildroot}/usr/local/bin/niova/

# ── Bundled C shared libraries (niova-raft + niova-pumicedb only) ────────────
# Installed to a private directory to avoid conflicts with system libraries.
# niova-core libs are NOT included here — they come from the niova-core RPM.
install -d %{buildroot}%{niova_libdir}

find %{niova_build}/lib -maxdepth 1 -name '*.so*' -type f \
    -exec install -m 0755 {} %{buildroot}%{niova_libdir}/ \;

find %{niova_build}/lib -maxdepth 1 -name '*.so*' -type l \
    -exec cp -a {} %{buildroot}%{niova_libdir}/ \;

# ── Remove invalid RPATHs from shared libraries ──────────────────────────────
find %{buildroot}%{niova_libdir} -name '*.so*' -type f \
    -exec chrpath -d {} \;

# ── Bundle dependency libraries (for standalone installation) ────────────────
# Copy RocksDB from build environment to niova-mdsvc lib dir
cp -a /usr/lib64/librocksdb.so.9* %{buildroot}%{niova_libdir}/
# Also bundle common dependencies from EPEL that might be missing
for lib in libgflags libsnappy; do
    find /usr/lib64 -name "${lib}.so*" -exec cp -a {} %{buildroot}%{niova_libdir}/ \;
done

# ── ldconfig drop-in ────────────────────────────────────────────────────────
install -d %{buildroot}/etc/ld.so.conf.d
install -m 0644 packaging/niova-mdsvc.conf \
    %{buildroot}/etc/ld.so.conf.d/niova-mdsvc.conf

# ── Scripts ─────────────────────────────────────────────────────────────────
install -d %{buildroot}/usr/share/niova-mdsvc/scripts
install -m 0755 scripts/deploy/deploy.sh \
    %{buildroot}/usr/share/niova-mdsvc/scripts/
install -m 0755 scripts/deploy/serf_gossip_interface.sh \
    %{buildroot}/usr/share/niova-mdsvc/scripts/
   

# ── Config example ──────────────────────────────────────────────────────────
install -m 0644 scripts/deploy/config.yaml \
    %{buildroot}/usr/share/niova-mdsvc/scripts/config.yaml.example

# ── systemd unit files ──────────────────────────────────────────────────────
install -d %{buildroot}/usr/lib/systemd/system
install -m 0644 packaging/niova-pmdbserver.service \
    %{buildroot}/usr/lib/systemd/system/
install -m 0644 packaging/niova-proxy.service \
    %{buildroot}/usr/lib/systemd/system/
install -m 0644 packaging/niova-monitor.service \
    %{buildroot}/usr/lib/systemd/system/

# ── Environment / config file ────────────────────────────────────────────────
install -d %{buildroot}/etc/niova
install -m 0640 packaging/niova.env %{buildroot}/etc/niova/niova.env

# ── Runtime directories ──────────────────────────────────────────────────────
install -d %{buildroot}/var/log/niova
install -d %{buildroot}/var/lib/niova
install -d %{buildroot}/var/lib/niova/configs
install -d %{buildroot}/var/lib/niova/ctl
install -d %{buildroot}/var/lib/niova/db

# ---------------------------------------------------------------------------
# %pre — runs before files are installed
# ---------------------------------------------------------------------------
%pre
getent group  niova > /dev/null || groupadd -r niova
getent passwd niova > /dev/null || \
    useradd -r -g niova \
            -d /var/lib/niova \
            -s /sbin/nologin \
            -c "Niova Control Plane service account" \
            niova

# ---------------------------------------------------------------------------
# %post — runs after files are installed
# ---------------------------------------------------------------------------
%post
/sbin/ldconfig

chown -R niova:niova /var/log/niova /var/lib/niova

if grep -q '^USER_ENCRYPTION_KEY=$' /etc/niova/niova.env 2>/dev/null; then
    GENERATED_KEY="$(openssl rand -base64 32)"
    sed -i "s|^USER_ENCRYPTION_KEY=$|USER_ENCRYPTION_KEY=${GENERATED_KEY}|" \
        /etc/niova/niova.env
    chown root:niova /etc/niova/niova.env
    echo "niova-mdsvc: generated USER_ENCRYPTION_KEY in /etc/niova/niova.env"
fi

%systemd_post niova-pmdbserver.service niova-proxy.service niova-monitor.service

echo ""
echo "==> niova-mdsvc installed."
echo ""
echo "Edit config.yaml (nodes, ports, output_dir, bin_dir, lib_dir), then run:"
echo ""
echo " deploy.sh -m init -t localhost <config.yaml> # first-time setup (cleans + generates configs)"
echo " deploy.sh -m restart -t localhost <config.yaml> # reuse configs and start services"
echo ""
echo "Modes:"
echo " init - fresh setup (wipes old state, creates configs)"
echo " restart - reuse existing configs (updates STORE paths)"
echo ""
echo "Types:"
echo " localhost - run everything on one node"
echo " distributed - deploy across nodes using pdsh"
echo ""
echo "Logs: <output_dir>/log/"
echo ""

# ---------------------------------------------------------------------------
# %preun
# ---------------------------------------------------------------------------
%preun
%systemd_preun niova-pmdbserver.service niova-proxy.service niova-monitor.service

# ---------------------------------------------------------------------------
# %postun
# ---------------------------------------------------------------------------
%postun
/sbin/ldconfig
%systemd_postun_with_restart niova-pmdbserver.service \
                              niova-proxy.service \
                              niova-monitor.service

# ---------------------------------------------------------------------------
# %files
# ---------------------------------------------------------------------------
%files

# Go binaries
%dir /usr/local/bin/niova
/usr/local/bin/niova/CTLPlane_pmdbServer
/usr/local/bin/niova/CTLPlane_proxy
/usr/local/bin/niova/cp-monitor
/usr/local/bin/niova/cc-manager

# Bundled C libraries — niova-raft + niova-pumicedb only
%dir %{niova_libdir}
%{niova_libdir}/*.so*

# ldconfig drop-in
/etc/ld.so.conf.d/niova-mdsvc.conf

# Scripts and example config
%dir /usr/share/niova-mdsvc
%dir /usr/share/niova-mdsvc/scripts
/usr/share/niova-mdsvc/scripts/start_pumice.sh
/usr/share/niova-mdsvc/scripts/gen_raft_cfgs.sh
/usr/share/niova-mdsvc/scripts/deploy.sh
/usr/share/niova-mdsvc/scripts/config.yaml.example

# systemd units
/usr/lib/systemd/system/niova-pmdbserver.service
/usr/lib/systemd/system/niova-proxy.service
/usr/lib/systemd/system/niova-monitor.service

# Environment file — noreplace: upgrades preserve operator edits
%dir /etc/niova
%config(noreplace) /etc/niova/niova.env

# Runtime directories owned by the niova user
%attr(0755, niova, niova) %dir /var/log/niova
%attr(0755, niova, niova) %dir /var/lib/niova
%attr(0750, niova, niova) %dir /var/lib/niova/configs
%attr(0750, niova, niova) %dir /var/lib/niova/ctl
%attr(0750, niova, niova) %dir /var/lib/niova/db

# ---------------------------------------------------------------------------
# %changelog
# ---------------------------------------------------------------------------
%changelog
* Wed Apr 08 2026 Niova Build System <build@niova.io> - 1.0.0-1
- Initial RPM release
- Bundles niova-raft and niova-pumicedb C libraries (niova-core is separate)
- Requires niova-core RPM for base C libraries
- systemd-managed deployment (niova-pmdbserver, niova-proxy, niova-monitor)
- x86_64 build
